In [1]:
import numpy as np
from IPython.display import Image
from IPython.core.display import HTML 

In [2]:
#四則運算 
array1 = np.arange(12).reshape(3,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
array2 = np.arange(12,24).reshape(3,4)
array2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
array1+array2 # np.add(a,b)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [5]:
array2-array1 # np.substract(a,b)

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [6]:
array1*array2 #np.multiply(a,b)

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [7]:
array1/array2 #np.divide(a,b)

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [8]:
array1%array2 #np.mod(a,b)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
#次方
array = np.arange(12).reshape(3,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
array**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [11]:
np.power(array,3)

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [12]:
#根號
array = np.arange(12).reshape(3,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
np.sqrt(array)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [14]:
#歐拉數 (Euler's number)
np.e

2.718281828459045

In [15]:
#指數函式 np.exp()
np.exp(1)

2.718281828459045

In [16]:
np.exp(array)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [17]:
#對數函式
np.log(array+1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [18]:
np.log2(array+1)

array([[0.        , 1.        , 1.5849625 , 2.        ],
       [2.32192809, 2.5849625 , 2.80735492, 3.        ],
       [3.169925  , 3.32192809, 3.45943162, 3.5849625 ]])

In [19]:
np.log10(array+1)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999],
       [0.95424251, 1.        , 1.04139269, 1.07918125]])

In [20]:
array_modified = np.log1p(array)
array_modified

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [21]:
np.round(array_modified) #四捨五取六入

array([[0., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [22]:
np.rint(array_modified)#round至最近整數

array([[0., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [23]:
np.trunc(array_modified)#無條件捨去

array([[0., 0., 1., 1.],
       [1., 1., 1., 2.],
       [2., 2., 2., 2.]])

In [24]:
np.floor(array_modified)#向下取整

array([[0., 0., 1., 1.],
       [1., 1., 1., 2.],
       [2., 2., 2., 2.]])

In [25]:
np.ceil(array_modified)#向上取整

array([[0., 1., 2., 2.],
       [2., 2., 2., 3.],
       [3., 3., 3., 3.]])

In [26]:
array = np.array(range(-5,5)).reshape(2,5)
print(array+0.5)
np.fix(array+0.5)#向0取整

[[-4.5 -3.5 -2.5 -1.5 -0.5]
 [ 0.5  1.5  2.5  3.5  4.5]]


array([[-4., -3., -2., -1., -0.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [27]:
#絕對值 
np.abs(array) #np.aabsolute(array)

array([[5, 4, 3, 2, 1],
       [0, 1, 2, 3, 4]])

In [28]:
np.fabs(array)# 不能處理複數

array([[5., 4., 3., 2., 1.],
       [0., 1., 2., 3., 4.]])

In [29]:
#點積 dot product
array1 = np.arange(12).reshape(3,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
array3 = np.arange(12).reshape(4,3)
array3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
np.dot([1,2],[7,8])

23

In [32]:
np.dot(array1,array3) #內積 向量投影長度

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [33]:
url = 'https://cumatrixfile.cupoy.com/000001754914E8680000001C6375706F795F72656C656173654349/marathon/1602735560935'
Image(url= url)

In [34]:
np.cross([1,2],[7,8])#外積 返回向量

array(-6)

In [35]:
np.cross([1,2,3],[7,8,9])#外積 返回向量

array([-6, 12, -6])

In [36]:
#外積
url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Sarrus_rule_cross_product.svg/220px-Sarrus_rule_cross_product.svg.png'
Image(url= url)

# HW

In [37]:
v1=20000
v0=20
GdB = 20*np.log10(v1/v0)
GdB

60.0

In [38]:
v50_v0 = 10**(50/20)
v50_v0

316.22776601683796

In [39]:
v30_v0 = 10**(30/20)
v30_v0

31.622776601683793

In [40]:
(v30_v0/v50_v0)

0.09999999999999999