In [1]:
import numpy as np

In [2]:
from IPython.display import Image
from IPython.core.display import HTML 

In [3]:
np.__version__

'1.18.5'

In [4]:
url = 'https://blog.finxter.com/wp-content/uploads/2019/10/grafik-1-1024x725.png'
Image(url= url)

In [5]:
#create Numpy array
array = np.array(range(0,20,1))
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
#Numpy array slicing
array_odd = array[0:20:2]
array_odd 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
array_3x = array[3:30:3]
array_3x

array([ 3,  6,  9, 12, 15, 18])