In [1]:
import numpy as np
import datetime

In [2]:
#np.isinf([np.inf, -np.inf, 1.0, np.nan, np.PINF])
# np.inf	正無限數	
# np.Inf	正無限數	
# np.Infinity	正無限數	
# np.PINF	正無限數	
# np.infty	正無限數	
# np.NINF	負無限數
array = np.array([1.0, np.nan, 3.0, float('inf'), float('-inf'), np.inf, np.NINF])

In [3]:
array

array([  1.,  nan,   3.,  inf, -inf,  inf, -inf])

In [4]:
#isnan
np.isnan(array)

array([False,  True, False, False, False, False, False])

In [5]:
#isfinite
np.isfinite(array)

array([ True, False,  True, False, False, False, False])

In [6]:
#isinf
np.isinf(array) 

array([False, False, False,  True,  True,  True,  True])

In [7]:
#isposinf
np.isposinf(array) 

array([False, False, False,  True, False,  True, False])

In [8]:
#isneginf
np.isneginf(array) 

array([False, False, False, False,  True, False,  True])

In [9]:
#isnat #not a time (日期類型) 
array = np.array(["NaT", "2020-06-26"], dtype="datetime64[ns]") #if not a time > T, else F
np.isnat(array) 

array([ True, False])

In [10]:
#如果陣列元素為純量或是數字物件 (例如實數、複數、有理數) 、內建常數、字串的話，
#isscalar() 回傳 True 。需要留意的是 isscalar() 不是 element-wise 的，所以傳入值須為元素。
array = np.array([1, 2, 3])
np.isscalar(array[2])

True

In [11]:
np.isscalar(array)

False

In [12]:
np.isscalar(np.pi)

True

In [13]:
np.isscalar(np.array(3.0))#陣列 依然是False

False

In [14]:
# 包含實數與複數的陣列
array = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])#1+1j == 複數

In [15]:
np.isreal(array)

array([False,  True,  True,  True,  True, False])

In [16]:
np.isrealobj(array)#判斷整個陣列物件是否為實數 

False

In [17]:
np.iscomplex(array)

array([ True, False, False, False, False,  True])

In [18]:
np.iscomplexobj(array)#判斷整個陣列物件是否為複數 （複數，為實數的延伸＝＝實數為複數的一種，但複數不一定是實數）

True

In [19]:
#np.array_equal()
#比較兩陣列是否形狀與元素完全相同
array1=np.array([1,2,3])
array2=np.array([1,2,3])
array3=np.array([-1,-2,-3])
np.array_equal(array1,array2)

True

In [20]:
np.array_equal(array1,array3)

False

In [21]:
#np.array_equiv()
#兩個陣列形狀元素值均相同，回傳 True；
#如果兩個陣列維度不同的話，須符合廣播規則，且元素值均相同，則回傳 True
np.array_equiv(np.array([1, 2, 3]), np.array([1, 2, 3]))

True

In [22]:
np.array_equiv(np.array([1, 2, 3]), np.array([[1, 2, 3], [1, 2, 3]]))

True

In [23]:
np.array_equiv(np.array([1, 1, 1]), np.array([1]))

True

In [24]:
np.array_equiv(np.array([1, 2, 1]), np.array([1]))

False

In [25]:
np.array_equiv(np.array([1, 2, 3]), np.array([[1, 2, 3], [1, 2, 1]]))

False

In [26]:
#np.equal() 
#np.not_equal()
#np.greater()
#np.greater_equal()
#np.less()
#np.less_equal()
#兩個陣列形狀元素值均相同，回傳 True；
#如果兩個陣列維度不同的話，須符合廣播規則，且元素值合條件，則回傳 True

In [27]:
# 形狀與元素值均相同
np.equal(np.array([1, 2, 3]), np.array([1, 2, 3]))

array([ True,  True,  True])

In [28]:
# 符合廣播規則的相等
np.equal(np.array([1, 1, 1]), np.ones(1))

array([ True,  True,  True])

In [29]:
# 不等於的比較，符合廣播規則
np.not_equal([1, 2], [[1, 3],[1, 4]])

array([[False,  True],
       [False,  True]])

In [30]:
np.greater([1, 2], [[1, 3],[1, 4]])

array([[False, False],
       [False, False]])

In [31]:
#np.logical_and()
#np.logical_or()
#np.logical_not()
#np.logical_xor()
#邏輯比較函式都是 element-wise，比較 2 個陣列元素。如果 2 個陣列的形狀不同的話，必須符合廣播 (broadcasting) 規則

In [32]:
x = np.array([True, True, False, False])
y = np.array([True, False, True, False])

In [33]:
np.logical_and(x,y) #only if both of them are True return True, others will be False

array([ True, False, False, False])

In [34]:
np.logical_or(x,y) #if any of them is True return True

array([ True,  True,  True, False])

In [35]:
np.logical_not(x) #work like != >>> not

array([False, False,  True,  True])

In [36]:
np.logical_xor(x, y) #work like ^ >>>相異 if 異 return True

array([False,  True,  True, False])

In [37]:
a = np.arange(5)
np.logical_and(a > 1, a < 4)

array([False, False,  True,  True, False])

In [38]:
a = np.arange(5)
np.logical_xor(a < 1, a > 3)

array([ True, False, False, False,  True])

In [39]:
#np.all() >>> and  (全部都是True 才回傳True)
#np.any() >>> or (任一是True, 回傳True)
#0, False >>> False
#True、NaN、正無限值、負無限值 >>> True

In [40]:
np.all([-1, np.nan, 5])

True

In [41]:
np.all([-1, 4, 0])

False

In [42]:
np.any([[True, False], [True, True]])

True

In [43]:
np.any([False, False])

False

In [44]:
np.any([[True, False], [False, False]], axis=0)

array([ True, False])

# HW

In [45]:
english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,55,60])

chinese_score = np.array([65,90,82,72,66,77])

- 上 3 列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文 55 分、數學 60 分、國文 65 分，運用上列數據回答下列問題。



- 有多少學生英文成績比數學成績高？ 3
- 是否全班同學最高分都是國文？ 是

In [46]:
np.greater(english_score,math_score)

array([False,  True,  True, False, False,  True])

In [47]:
np.greater(english_score,math_score)*1

array([0, 1, 1, 0, 0, 1])

In [48]:
np.sum(np.greater(english_score,math_score)*1)

3

In [49]:
np.logical_and(chinese_score>math_score,chinese_score>english_score)

array([ True,  True,  True,  True,  True,  True])