In [1]:
import numpy as np
from IPython.display import Image

In [2]:
#點積 (dot product)
#np.dot()
Image(url= "http://cumatrixfile.cupoy.com/0000017549469591000000226375706F795F72656C656173654349/marathon/1602735561008")

In [3]:
np.random.seed(9)
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)


In [4]:
np.dot(A,B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [5]:
#內積 (inner product)
Image(url= "http://cumatrixfile.cupoy.com/0000017549469591000000226375706F795F72656C656173654349/marathon/1602735561009")
#a0b0 + a1b1 +...
#np.inner(a, b)


In [6]:
A = np.arange(6).reshape(6,1)
B = np.arange(12).reshape(12, 1)
np.inner(A,B) # 2 個一維陣列(向量)做內積

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55]])

In [7]:
#多維陣列做乘積那麼最後維度必須要符合(最後一層(axis = -1)之形狀需相符），而內積結果就是其元素相乘之和
A = np.arange(18).reshape(3, 2, 3)
B = np.arange(36).reshape(4, 3, 3)
np.inner(A,B)
#5 = 0,1,2*0,1,2
#14 = 0,1,2*3,4,5
#23 = 0,1,2*6,7,8
#32 = 0,1,2*9,10,11

array([[[[   5,   14,   23],
         [  32,   41,   50],
         [  59,   68,   77],
         [  86,   95,  104]],

        [[  14,   50,   86],
         [ 122,  158,  194],
         [ 230,  266,  302],
         [ 338,  374,  410]]],


       [[[  23,   86,  149],
         [ 212,  275,  338],
         [ 401,  464,  527],
         [ 590,  653,  716]],

        [[  32,  122,  212],
         [ 302,  392,  482],
         [ 572,  662,  752],
         [ 842,  932, 1022]]],


       [[[  41,  158,  275],
         [ 392,  509,  626],
         [ 743,  860,  977],
         [1094, 1211, 1328]],

        [[  50,  194,  338],
         [ 482,  626,  770],
         [ 914, 1058, 1202],
         [1346, 1490, 1634]]]])

In [8]:
A

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [9]:
B

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [10]:
#外積 (outer product) ==張量積
#2 個一維陣列(向量)做計算
#若非一維陣列的話會先進行展平(flatten)再進行外積
Image(url= "http://cumatrixfile.cupoy.com/0000017549469591000000226375706F795F72656C656173654349/marathon/1602735561010")


In [11]:
np.random.seed(9)
a = np.random.randint(10, size=(5))
b = np.random.randint(10, size=(6))

In [12]:
a

array([5, 6, 8, 6, 1])

In [13]:
b

array([6, 4, 8, 1, 8, 5])

In [14]:
np.outer(a, b)

array([[30, 20, 40,  5, 40, 25],
       [36, 24, 48,  6, 48, 30],
       [48, 32, 64,  8, 64, 40],
       [36, 24, 48,  6, 48, 30],
       [ 6,  4,  8,  1,  8,  5]])

In [15]:
A = np.arange(6).reshape(3, 2)
B = np.arange(4).reshape(2, 2)

In [16]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
B

array([[0, 1],
       [2, 3]])

In [18]:
#A >>> [0,1,2,3,4,5]
#B >>> [0,1,2,3]
np.outer(A, B)

array([[ 0,  0,  0,  0],
       [ 0,  1,  2,  3],
       [ 0,  2,  4,  6],
       [ 0,  3,  6,  9],
       [ 0,  4,  8, 12],
       [ 0,  5, 10, 15]])

In [19]:
# matmul 與 @

In [20]:
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)

In [21]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
A@B
#20 = 0*0+1*4+2*8
#23 = 0*1+1*5+2*9

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [24]:
#跡(trace) 取左上至右下斜線之和
#np.trace()
Image(url= "http://cumatrixfile.cupoy.com/0000017549469591000000226375706F795F72656C656173654349/marathon/1602735561013")

In [25]:
np.trace(A)
#4 = 0+4

4

In [26]:
np.trace(B)
#15 = 0+5+10

15

In [27]:
#行列式(determinant) must be square
#np.linalg.det(A)
Image(url= "http://cumatrixfile.cupoy.com/0000017549469591000000226375706F795F72656C656173654349/marathon/1602735561014")

In [28]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
np.linalg.det(A)

0.0

In [30]:
#反矩陣(inverse) must be square
#np.linalg.inv()
Image(url= "http://cumatrixfile.cupoy.com/0000017549469591000000226375706F795F72656C656173654349/marathon/1602735561015")

In [31]:
A = np.array([[3, 0, -1],[2, 4, 1],[7, 2, 3]])
A

array([[ 3,  0, -1],
       [ 2,  4,  1],
       [ 7,  2,  3]])

In [32]:
np.linalg.inv(A)

array([[ 0.18518519, -0.03703704,  0.07407407],
       [ 0.01851852,  0.2962963 , -0.09259259],
       [-0.44444444, -0.11111111,  0.22222222]])

In [33]:
#轉置 (Transpose)
#np.transpose()
Image(url= "http://cumatrixfile.cupoy.com/0000017549469591000000226375706F795F72656C656173654349/marathon/1602735561016")

In [34]:
np.transpose(A)

array([[ 3,  2,  7],
       [ 0,  4,  2],
       [-1,  1,  3]])

In [35]:
#特徵值與特徵向量(eig)
#eig() 函式可以用來計算方陣的特徵值(eigenvalue)與特徵向量(eigenvector)。
#eig() 回傳值有2個：eigenvalues, eigenvectors。
eigenvalues, eigenvectors = np.linalg.eig(A)
print('特徵值：',eigenvalues,'\n','特徵向量： ', eigenvectors)

特徵值： [3.18531916+2.175406j 3.18531916-2.175406j 3.62936168+0.j      ] 
 特徵向量：  [[ 0.03151526-0.36994819j  0.03151526+0.36994819j  0.25758438+0.j        ]
 [-0.18541585+0.41309627j -0.18541585-0.41309627j -0.95255941+0.j        ]
 [-0.81062788+0.j         -0.81062788-0.j         -0.16211374+0.j        ]]


In [36]:
#eigvals() 函式也可以計算特徵值。
np.linalg.eigvals(A)

array([3.18531916+2.175406j, 3.18531916-2.175406j, 3.62936168+0.j      ])

In [37]:
#秩(rank) 
np.linalg.matrix_rank(A)

3

In [38]:
#線性系統求解(solve)
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x
#3x+y = 9
#x +2y=8
#解 x=2 y=3

array([2., 3.])

In [39]:
#單位矩陣(identity)
#單位矩陣是對角線元素值為 1 的方陣。
Image(url= "http://cumatrixfile.cupoy.com/0000017549469591000000226375706F795F72656C656173654349/marathon/1602735561021")

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
#單位矩陣(eye)
# eye() 產生的可以不是方陣，也可以指定對角線開始的索引。
Image(url= "http://cumatrixfile.cupoy.com/0000017549469591000000226375706F795F72656C656173654349/marathon/1602735561023")

In [42]:
np.eye(5,4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [44]:
#單對角陣列(Diagonal)
A = np.array([[3, 4, 0], [4, 4, 6], [0, 6, 5]])
A

array([[3, 4, 0],
       [4, 4, 6],
       [0, 6, 5]])

In [45]:
np.diagonal(A, offset=0)

array([3, 4, 5])

In [46]:
np.diagonal(A, offset=1)

array([4, 6])

In [47]:
#三角矩陣(tri)
#可以用來產生對角線以下都是 1 的元素
Image(url= "http://cumatrixfile.cupoy.com/0000017549469591000000226375706F795F72656C656173654349/marathon/1602735561026")

In [48]:
np.tri(4,4,k=0)#k=0 表對角線後第一格

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [49]:
np.tri(4,4,k=1)#k=1 表對角線後第二格

array([[1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
#上三角矩陣(Upper Triangular)
#triu()

#下三角矩陣(Lower Triangular)
#numpy.tril()

#可將對角線以上或以下的元素值設為 0，也可以指定對角線起始的索引。

In [51]:
A = np.array([[3, 4, 1], [4, 4, 6], [3, 6, 5]])
A

array([[3, 4, 1],
       [4, 4, 6],
       [3, 6, 5]])

In [52]:
np.triu(A)#保留upper, 改變lower

array([[3, 4, 1],
       [0, 4, 6],
       [0, 0, 5]])

In [53]:
np.tril(A)#保留lower,改變upper

array([[3, 0, 0],
       [4, 4, 0],
       [3, 6, 5]])

In [54]:
np.tril(A,k=1)#保留lower,改變upper

array([[3, 4, 0],
       [4, 4, 6],
       [3, 6, 5]])

In [55]:
#矩陣分解 (Matrix Decomposition)
#是將一個矩陣拆解為數個矩陣的乘積的運算
B = np.array([[1, 2],[2, 50]])
B


array([[ 1,  2],
       [ 2, 50]])

In [56]:
#Cholskey Decomposition
#np.linalg.cholesky()

np.linalg.cholesky(B)

array([[1.        , 0.        ],
       [2.        , 6.78232998]])

In [57]:
#QR Factorization
#np.linalg.qr()
q, r = np.linalg.qr(B)
q

array([[-0.4472136 , -0.89442719],
       [-0.89442719,  0.4472136 ]])

In [58]:
r

array([[ -2.23606798, -45.61578674],
       [  0.        ,  20.57182539]])

In [59]:
#Singular Value Decomposition (SVD)
#np.linalg.svd()
u, s, vh = np.linalg.svd(B)

In [60]:
u

array([[ 0.04071476,  0.99917081],
       [ 0.99917081, -0.04071476]])

In [61]:
s

array([50.08149711,  0.91850289])

In [62]:
vh

array([[ 0.04071476,  0.99917081],
       [ 0.99917081, -0.04071476]])

# HW

In [63]:
array1 = np.array([[10, 8], [3, 5]])
array1

array([[10,  8],
       [ 3,  5]])

In [64]:
# 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1_inv = np.linalg.inv(array1)
print(array1.dot(array1_inv))

[[1. 0.]
 [0. 1.]]


In [65]:
# 運用上列array計算特徵值、特徵向量?
eigenvalues, eigenvectors = np.linalg.eig(array1)
print(eigenvalues, '\n',eigenvectors)

[13.  2.] 
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [66]:
# 運用上列array計算SVD?
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))