In [1]:
import numpy as np

In [2]:
#flatten() / ravel()
array = np.array(range(0,20)).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
array.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
array.ravel()[0]=100#在 ravel() 回傳物件中做的元素值變更，將會影響原陣列的元素值。

In [6]:
array

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [7]:
#reshape() must 剛好總元素個數相等
array = np.array(range(0,20)).reshape(3,8)
array

ValueError: cannot reshape array of size 20 into shape (3,8)

In [8]:
#reshape() must 剛好總元素個數相等
array = np.array(range(0,20)).reshape(3,3)
array

ValueError: cannot reshape array of size 20 into shape (3,3)

In [9]:
#reshape() 若大小超過元素總值，會補上
array = np.array(range(0,20)).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
#resize() 若大小超過元素總值，會補上
np.resize(array,(4,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9, 10, 11]])

In [11]:
np.resize(array,(4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
#axis j*q*k (axis0 = j, axis1 = q, axis2 = k)
#dimension 3 (共三個)
array = np.array(range(0,36)).reshape(2,2,9)
array

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]]])

In [13]:
array = np.array(range(0,36)).reshape(2,2,3,3)

In [14]:
#concatenate() 形狀相同可合併
array1 = np.arange(6).reshape(3,2)
array1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
array2 = np.arange(6).reshape(3,2)
array2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
np.concatenate((array1,array2),axis=0,out=None) #6*2

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [17]:
np.concatenate((array1,array2),axis=1) #3*4

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [18]:
np.stack((array1,array2),axis = 0)# 現為2*3*2的三維 原本為 2*3的二維

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]])

In [19]:
np.hstack((array1,array2)) #3*4

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [20]:
np.vstack((array1,array2)) #6*2

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [21]:
#split
array = np.arange(9).reshape(3,3)
np.split(array,3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [22]:
array = np.arange(9).reshape(3,3)
np.split(array,3, axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [23]:
#hsplit() 直的切
array = np.arange(6).reshape(3,2)
np.hsplit(array,2)

[array([[0],
        [2],
        [4]]), array([[1],
        [3],
        [5]])]

In [24]:
#vsplit() 橫的切
array = np.arange(6).reshape(3,2)
np.vsplit(array,3)

[array([[0, 1]]), array([[2, 3]]), array([[4, 5]])]

In [25]:
#NumPy 陣列迭代 以axis 0 為基準
array = np.arange(6).reshape(3,2)
print(array,'\n')
for row in array:
    print(row)

[[0 1]
 [2 3]
 [4 5]] 

[0 1]
[2 3]
[4 5]


In [26]:
#NumPy 陣列搜尋與排序 - amax()、amin()、max()、min()
array = np.arange(6).reshape(3,2)
print(array)
np.amax(array)

[[0 1]
 [2 3]
 [4 5]]


5

In [27]:
np.amin(array)

0

In [28]:
array.max()

5

In [29]:
array.min()

0

In [30]:
np.amax(array,axis=1,keepdims=False)

array([1, 3, 5])

In [31]:
np.amax(array,axis=0,keepdims=False)

array([4, 5])

In [32]:
array = np.arange(36).reshape(3,2,6)
print(array)
np.amin(array,axis=0)#針對"3"*2*9

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [33]:
array = np.arange(36).reshape(3,2,6)
print(array)
np.amin(array,axis=1)#針對3*"2"*9

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [34]:
array = np.arange(36).reshape(2,2,9)
print(array)
np.amin(array,axis=0)#針對"2"*2*9

[[[ 0  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]]

 [[18 19 20 21 22 23 24 25 26]
  [27 28 29 30 31 32 33 34 35]]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [35]:
array = np.arange(36).reshape(2,2,9)
print(array)
np.amin(array,axis=1)#針對2*"2"*9

[[[ 0  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]]

 [[18 19 20 21 22 23 24 25 26]
  [27 28 29 30 31 32 33 34 35]]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [36]:
array = np.arange(36).reshape(2,2,9)
print(array)
np.amax(array,axis=1)

[[[ 0  1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16 17]]

 [[18 19 20 21 22 23 24 25 26]
  [27 28 29 30 31 32 33 34 35]]]


array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [37]:
#NumPy 陣列搜尋與排序 – argmax() 與 argmin() #回傳index
array = np.array(range(0,-36,-1)).reshape(3,2,6)
print(array)
array.argmax()

[[[  0  -1  -2  -3  -4  -5]
  [ -6  -7  -8  -9 -10 -11]]

 [[-12 -13 -14 -15 -16 -17]
  [-18 -19 -20 -21 -22 -23]]

 [[-24 -25 -26 -27 -28 -29]
  [-30 -31 -32 -33 -34 -35]]]


0

In [38]:
array = np.array(range(0,-36,-1)).reshape(3,2,6)
array.argmin()

35

In [39]:
array.argmax(axis=0)#針對"3"*2*6的形狀 回傳該最大值之index

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [40]:
array.argmax(axis=1)#針對3*“2”*6的形狀  回傳該最大值之index

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [41]:
#NumPy 陣列搜尋與排序 – where(condition, x, y)  # like (if x_condition, x_True, x_False)
array = np.array(range(18,-18,-1)).reshape(3,2,6)
print(array)
np.where(array>0,1,0)#此處array 其實是[for i in array]

[[[ 18  17  16  15  14  13]
  [ 12  11  10   9   8   7]]

 [[  6   5   4   3   2   1]
  [  0  -1  -2  -3  -4  -5]]

 [[ -6  -7  -8  -9 -10 -11]
  [-12 -13 -14 -15 -16 -17]]]


array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [42]:
#NumPy 陣列搜尋與排序 – nonzero()
array = np.zeros((2,2,3))
print(array)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [43]:
array[0][1][2]=1
array[1][1][1]=1
print(array)
np.nonzero(array)#retrun index where element is not 0
#([0][1][2])
#([1][1][1])

[[[0. 0. 0.]
  [0. 0. 1.]]

 [[0. 0. 0.]
  [0. 1. 0.]]]


(array([0, 1]), array([1, 1]), array([2, 1]))

In [44]:
#NumPy 陣列搜尋與排序 – sort() 與 argsort() ：index 參數 選擇僅針對的部位排序 e.g. -1 >>>最後一個axis which is 6
#sort()回傳陣列
#argsort() 回傳索引
array = np.array(range(18,-18,-1)).reshape(3,2,6)
array.sort(axis=-1)#inplace
array

array([[[ 13,  14,  15,  16,  17,  18],
        [  7,   8,   9,  10,  11,  12]],

       [[  1,   2,   3,   4,   5,   6],
        [ -5,  -4,  -3,  -2,  -1,   0]],

       [[-11, -10,  -9,  -8,  -7,  -6],
        [-17, -16, -15, -14, -13, -12]]])

In [45]:
array = np.array(range(18,-18,-1)).reshape(3,2,6)
np.sort(array,axis=0)

array([[[ -6,  -7,  -8,  -9, -10, -11],
        [-12, -13, -14, -15, -16, -17]],

       [[  6,   5,   4,   3,   2,   1],
        [  0,  -1,  -2,  -3,  -4,  -5]],

       [[ 18,  17,  16,  15,  14,  13],
        [ 12,  11,  10,   9,   8,   7]]])

In [46]:
array = np.array(range(18,-18,-1)).reshape(3,2,6)
array.argsort(axis=1)#inplace
array

array([[[ 18,  17,  16,  15,  14,  13],
        [ 12,  11,  10,   9,   8,   7]],

       [[  6,   5,   4,   3,   2,   1],
        [  0,  -1,  -2,  -3,  -4,  -5]],

       [[ -6,  -7,  -8,  -9, -10, -11],
        [-12, -13, -14, -15, -16, -17]]])

In [47]:

array = np.array(range(18,-18,-1)).reshape(3,2,6)
np.argsort(array)

array([[[5, 4, 3, 2, 1, 0],
        [5, 4, 3, 2, 1, 0]],

       [[5, 4, 3, 2, 1, 0],
        [5, 4, 3, 2, 1, 0]],

       [[5, 4, 3, 2, 1, 0],
        [5, 4, 3, 2, 1, 0]]])

# HW

In [48]:
array1 = np.array(range(30))
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [49]:
#order : {'C', 'F', 'A'} 
#C: 行
#F: 列
array1.reshape(5,6,order='F')

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [50]:
array1.reshape(5,6,order='C')

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
print(np.where(array1.reshape(5,6,order='F')%6==1,1,0))
np.where(array1.reshape(5,6,order='F')%6==1,1,0).nonzero()

[[0 0 0 0 0 1]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]


(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))